### ISSUE TITLE
Not getting incoming message

### ISSUE THREAD

**Issue by pranavpari** [arduino-libraries/ArduinoMqttClient#13]
Hello, 
I am not getting an incoming message for a subscribed topic

**Comment by sandeepmistry** [comment]
Hi @pranavpari,

Could you please provide more details, such as:
- What board(s) you are using
- Minimal sketch to reproduce the issue
- Broker you are using

**Comment by pranavpari** [comment]
I am using arduino uno with esp8266 esp-01 and simply connecting it to CloudMQTT server

**Comment by sandeepmistry** [comment]
Please provide the other details requested in https://github.com/arduino-libraries/ArduinoMqttClient/issues/13#issuecomment-532688457.

**Comment by aentinger** [comment]
Hi @pranavpari :wave: I'm closing this since there was no feedback from you since 19/09/2019. Please reopen if this is still relevant providing the information outlined in https://github.com/arduino-libraries/ArduinoMqttClient/issues/13#issuecomment-532688457.
