### ISSUE TITLE
use token to connect rather than login/password

### ISSUE THREAD

**Issue by jlidgard** [arduino-libraries/ArduinoMqttClient#21]
Would it be possible to add functionality to enable the use of tokens?

**Comment by sandeepmistry** [comment]
Hi @jlidgard,

From my knowledge, tokens are not part of the MQTT standard. Could you please provide some more details on the MQTT broker you are trying to connect to?

**Comment by aentinger** [comment]
Hi @jlidgard :wave: I'm closing this since there was no feedback from you since 14/11/2019. Please reopen if this is still relevant providing the information requested in https://github.com/arduino-libraries/ArduinoMqttClient/issues/21#issuecomment-554048359 .
