### ISSUE TITLE
MQTT connection causes sensors to stop collecting data

### ISSUE THREAD

**Issue by JDuchniewicz** [arduino-libraries/ArduinoMqttClient#54]
When I call `mqttClient.connect()` my sensors stop collecting data. I looked briefly at the code but nothing looks like it would be blocking I2C (which is used for sensor data collection).

**Comment by per1234** [comment]
Hi @JDuchniewicz. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there:

https://forum.arduino.cc/

**Comment by JDuchniewicz** [comment]
It looks like the problem is bus contention due to ECCX08 secure element. This is unrelated to this library.
