### ISSUE TITLE
SSL/TLS with Aduino UNO Wifi REV2

### ISSUE THREAD

**Issue by hezro93** [arduino-libraries/ArduinoMqttClient#77]
How can i connect Arduino Uno Wifi REV2 with AWS (Amazon Web Server) for an IoT application. I tried following this tutorial to connect to AWS Iot and kept getting errors: https://docs.arduino.cc/tutorials/mkr-wifi-1010/securely-connecting-an-arduino-mkr-wifi-1010-to-aws-iot-core.
I'm having a problem with the key is too large for my Arduino. What should I do? The bug is:
Sketch uses 207536 bytes (426%) of program storage space. Maximum is 48640 bytes.
text section exceeds available space in board
Global variables use 16050 bytes (261%) of dynamic memory, leaving -9906 bytes for local variables. Maximum is 6144 bytes.
Sketch too big; see http://www.arduino.cc/en/Guide/Troubleshooting#size for tips on reducing it.
Error compiling for board Arduino Uno WiFi Rev2.

**Comment by per1234** [comment]
Hi @hezro93. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
