### ISSUE TITLE
can not set setKeepAliveInterval

### ISSUE THREAD

**Issue by hanlong-coclean** [arduino-libraries/ArduinoMqttClient#79]
i use setKeepAliveInterval to set keepalive time ,and use my phone as AP,and in loop cycle to check  status of connected() , but no matter which value i set, it allways alert me the mqtt is disconnected after 10 seconds when i turn off the AP of my phone.
how can i adjust the keepaliveinterval.

**Comment by per1234** [comment]
Hi @hanlong-coclean. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
