### ISSUE TITLE
Giga R1 WiFi works with a small change

### ISSUE THREAD

**Issue by esp32beans** [arduino-libraries/ArduinoMqttClient#85]
I tested ver 0.1.6 using Giga R1 WiFi. Only a small change is required to make the examples work. I removed the check for ESP32 because Giga also uses WiFi.h.

Old
```
#elif defined(ESP32)
  #include <WiFi.h>
#endif
```

New
```
#else
  #include <WiFi.h>
#endif
```
Is it too much to hope new boards will implement the standard Arduino WiFi API? For example, Uno R4 will have a WiFi option. Would be nice to avoid releasing a new version  of the library whenever a new board with WiFi appears.

**Comment by aentinger** [comment]
I've fixed this library.

It would probably pay off to do a new release of this library, any objections @pennam ?

**Comment by pennam** [comment]
Not at all. Thanks @aentinger :+1:

**Comment by aentinger** [comment]
Done https://github.com/arduino-libraries/ArduinoMqttClient/releases/tag/0.1.7 :wink: :bow:
