### ISSUE TITLE
Add Uno R4 WiFi support to examples

### ISSUE THREAD

**Issue by ShortArrow** [arduino-libraries/ArduinoMqttClient#94]
# Expected

Need const like `UNO_R4_WIFI`. 
And include `WiFiS3.h`.

Note: this is tested by my Uno R4 WiFi.

```cpp
#include <ArduinoMqttClient.h>
#include <WiFiS3.h>
#include "arduino_secrets.h"
```

# Actual

https://github.com/arduino-libraries/ArduinoMqttClient/blob/107090e420563295a586fd8bd44dc0cbff77a889/examples/WiFiSimpleReceive/WiFiSimpleReceive.ino#L14-L22

https://github.com/arduino-libraries/ArduinoMqttClient/blob/107090e420563295a586fd8bd44dc0cbff77a889/examples/WiFiSimpleSender/WiFiSimpleSender.ino#L14-L22

**Comment by jwilleke** [comment]
Works for me with 
``` c++
#include <ArduinoMqttClient.h>
#include <SPI.h>
#include <PubSubClient.h>
#include "WiFi.h"
#include <WiFiClient.h>
```
